### PR TITLE
ESlint + fixes

### PR DESCRIPTION
**Pull request by akx**
This PR:

* Configures ESLint (and Prettier, though it's not in use) for the repository.
  * The base rules are the Airbnb rules, but with plenty of rules disabled for the time being to make things a little easier for now.
  * The `static/` directory is not being linted right now, even if the frontend files (`spx_*`) in there probably would benefit from it.
* Fixes many ESlint `no-undef` problems, mostly by way of
  * adding `global.` to where e.g. `io` or `config` is accessed
  * adding `const`/`let`/`var` where it was missing (which may also fix some wonky behavior from variables leaking)
* Fixes `no-unused-vars` errors, some of which are fixed by getting rid of `eval`s in favor of safer methods
* Fixes _most_ other errors encountered
* Adds a GitHub Actions workflow that runs ESLint.

It should be noted that the workflow does currently fail because there are some uses of `eval` left I couldn't make heads or tails of, and some other things I didn't quite bother to change right now.

### CODE REVIEW

**Comment by akx** [comment]
@TuomoKu Ping :)

**Comment by TuomoKu** [comment]
@akx Thanks for your PR. Great stuff and tons of improvements. I have looked into it briefly but cannot merge as-is, since it seem to break some of the functionality (such as localized UI strings) and most likely some playout functions on CasparCG.
Linting is a great addition to the entire dev workflow.

I will try to find time to do a review, hopefully this week.

**Comment by akx** [comment]
> since it seem to break some of the functionality (such as localized UI strings) and most likely some playout functions on CasparCG.


I was afraid the former could be the case if the localized ui strings' keys use dot notation. I'd suggest using the Lodash library's `get` helper for those then.

**Comment by akx** [comment]
Closing. No point trying to rebase this after such a long time.

**Pull request closed without merging**
